
services:
  weaviate_anon:
    image: cr.weaviate.io/semitechnologies/weaviate:1.29.1
    command: [ "--host","0.0.0.0","--port","8080","--scheme","http" ]
    ports:
      - "8080:8080"
      - "50051:50051"
    restart: on-failure:0
    environment:
      - QUERY_DEFAULTS_LIMIT=25
      - AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED=true
      - PERSISTENCE_DATA_PATH=/var/lib/weaviate
      - ENABLE_API_BASED_MODULES=true
      - BACKUP_FILESYSTEM_PATH=/var/lib/weaviate/backups
      - CLUSTER_HOSTNAME=node1
      - CORS_ALLOWED_ORIGINS=http://localhost:8081

  weaviate_console:
    image: semitechnologies/weaviate-console:latest
    ports:
      - "8081:80"
    depends_on:
      - weaviate_anon
    environment:
      - WEAVIATE_URL=http://weaviate_anon:8080
